### ISSUE TITLE
> Thanks for using tocbot. I just updated the readme to explain how to handle fixed headers better. [tscanlin/tocbot#fixed-headers](https://github.com/tscanlin/tocbot#fixed-headers)

### ISSUE THREAD

**Issue by tscanlin** [tscanlin/tocbot#133]
> Thanks for using tocbot. I just updated the readme to explain how to handle fixed headers better. [tscanlin/tocbot#fixed-headers](https://github.com/tscanlin/tocbot#fixed-headers)
> 
> Basically, use CSS similar to the following:
> 
> ```css
> h1::before, h2::before, h3::before, h4::before, h5::before, h6::before {
>     display: block;
>     content: " ";
>     height: 60px;
>     margin-top: -60px;
>     visibility: hidden;
> }
> ```
> 
> Let me know how that works for you.

Do you have to set `headingSelector: 'h2::before, h3::before, h4::before'` for this to work? I tried that and it says `Element not found: .post-content` where `.post-content` is my `contentSelector`.

If I remove the `::before` tags then nothing happens and it still scrolls to the top.

Thanks for your help!

_Originally posted by @y1zhou in https://github.com/tscanlin/tocbot/issues/58#issuecomment-476348872_

**Comment by tscanlin** [comment]
The heading selector doesn't need to change for this. Can you link me to an example of this hosted somewhere? I suspect it's because of when / how you are initializing tocbot. This should happen once all your DOM content has been loaded / rendered.

**Comment by y1zhou** [comment]
Sure! My apologies for spamming the earlier issue.

The way I'm initializing tocbot is:

```js
<script src="https://cdn.jsdelivr.net/npm/tocbot@4.5.1/dist/tocbot.min.js"
    integrity="sha256-/ckfJgTIsKUdmu0l4sDCwy4esp5MDVjYmY905r9Nt3M=" crossorigin="anonymous"></script>
<script>
    tocbot.init({
        // Where to render the table of contents.
        tocSelector: '.toc',
        // Where to grab the headings to build the table of contents.
        contentSelector: '.post-content',
        // Which headings to grab inside of the contentSelector element.
        headingSelector: 'h2, h3, h4',
        // Timeout between events firing to make sure it's
        // not too rapid (for performance reasons).
        throttleTimeout: 200
    });
</script>
```
and the CSS used is:
```css
.post-full-content h2::before,
.post-full-content h3::before,
.post-full-content h4::before {
    display: block;
    content: ' ';
    height: 70px;
    margin-top: -70px;
    visibility: hidden;
    overflow: hidden;
}
```

The page I'm testing is [this](https://y1zhou.com/fundamentals-nonparametric/). The expected behavior is when I click on a link in the TOC, the page would scroll to the position where the header is `70px` under the top. However, now it still scrolls all the way to the top.

 Again, thanks a lot for your work and help!

**Comment by tscanlin** [comment]
This was a tricky one. Seems to be a strange CSS thing going on..

try setting:
```
h1, h2, h3, h4, h5, h6 {
    padding-top: 0;
}
```

For some reason padding on the headings seemed to mess this up. Can you try that and let me know if it works?

**Comment by y1zhou** [comment]
@tscanlin Added, but didn't notice any difference. It is weird... I checked my other CSS files and no `::before` for the headers were found. `padding: 0` also seemed to be defined already in `global.css`.

**Comment by tscanlin** [comment]
I had just tested it on the tocbot docs site. On your site I'm still not quite sure what's going on but its most likely due to other styling on the page because when I use chrome local overrides to delete all of the css in screen.css it works as expected and there is a gap above all of the headings. I'd try to remove / unstyle some of your page wrappers as they may be messing with it.

**Comment by y1zhou** [comment]
@tscanlin It's too complicated for a beginner like me to mess with, so I'm going with the other fix:

```css
.post-full-content h2,
.post-full-content h3,
.post-full-content h4 {
    padding-top: 70px;
    margin-top: -70px;
}
.post-full-content h2:focus,
.post-full-content h3:focus,
.post-full-content h4:focus {
    outline: none;
    text-decoration: underline;
}
```

Thanks!
