### ISSUE TITLE
Active section not set correctly if section has no content

### ISSUE THREAD

**Issue by asprouse5** [tscanlin/tocbot#253]
I noticed that if a section has no or very little content the active section isn't set correctly. See https://jsfiddle.net/1ctge5my/1/, also summarized below. In the fiddle the section header appears behind the fixed header but I'm not seeing that issue on my site.

To reproduce: Click on "Three", then click on "One". I would expect "One" to be the active section, but it's actually "Two". I suspect the headingsOffset has something to do with it, but I think I need to use that for my fixed header. Uncomment the paragraph in the first section and it works as expected.

```html
<div id="header"></div>
<div>
  <div id="box">
    <div id="sections">
      <section>
        <header>
          <h2 id="One">One</h2>
        </header>
        <!-- <p>
          One Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p> -->
      </section>
      <section>
        <header>
          <h2 id="Two">Two</h2>
        </header>
        <p>
          Two Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
      </section>
      <section>
        <header>
          <h2 id="Three">Three</h2>
        </header>
        <p>
          Three Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
        </p>
      </section>
    </div>
    <div id="toc"></div>
  </div>
</div>
```
```css
body {
  min-height: 1000px;
  position: absolute;
  top: 50px;
  bottom: 0;
  overflow: auto;
}

#header {
  position: fixed;
  top: 0;
  height: 50px;
  width: 100%;
  background-color: blue;
}

#box {
  display: flex;
}

#toc {
  position: sticky;
  top: 60px;
  align-self: flex-start;
}

.toc-list {
  list-style: none;
}
```

```js
tocbot.init({
  tocSelector: '#toc',
  contentSelector: '#sections',
  headingSelector: 'h2',
  headingsOffset: 50,
  scrollSmooth: false
});
```
