### ISSUE TITLE
Tocbot offset wrong on first click and works after second click 

### ISSUE THREAD

**Issue by khanakia** [tscanlin/tocbot#254]
Talbot offset wrong on first click and works after the second click

**Comment by tscanlin** [comment]
Hi, can you link me to an example of this issue being reproduced somewhere?

**Comment by khanakia** [comment]
I just checked again so the issue happens when `scrollSmooth: true` is set to TRUE.
Here is the link https://blog1.khanakia.com/pages/terms#monitoring-and-enforcement-termination

**Comment by tscanlin** [comment]
Hmm, the example link you posted is not working for me. I get a 502 error.

**Comment by khanakia** [comment]
I am sorry. Check now it should work

**Comment by tscanlin** [comment]
hmm, looks like I am getting a 404 now

**Comment by khanakia** [comment]
Please check this link https://blog1.khanakia.com/terms1?nocahe#trademarks

**Comment by tscanlin** [comment]
Some of your heading appear to be missing IDs. All of your headings must have ID's for it to work properly.

**Comment by khanakia** [comment]
@tscanlin Please check screenshot all the h tags has ID

```
document.querySelectorAll("h1,h2,h3,h4,h5")
```

<img width="661" alt="Screenshot 2021-12-02 at 12 57 06 PM" src="https://user-images.githubusercontent.com/2174170/144376936-b4e3f9e6-1780-4811-89da-a12f22e52b74.png">

**Comment by tscanlin** [comment]
It seems like the JS solution for the fixed header isn't working on that site for some reason. You could try the following CSS solution though:

```css
h1::before, h2::before, h3::before, h4::before, h5::before, h6::before {
    display: block;
    content: " ";
    height: 60px;
    margin-top: -60px;
    visibility: hidden;
}
```
