### ISSUE TITLE
Selected TOC element scrolls under fixed header

### ISSUE THREAD

**Issue by dankoster** [tscanlin/tocbot#58]
Hey, I have a site with a fixed header (style="position: fixed;"). When I click an item in the TOC, the selected element scrolls to the top of the page, as expected, but ends up underneath the fixed header. I have tried setting headingsOffset to the height of the header, but it seems to have no effect. Am I missing an option for this situation?

**Comment by tscanlin** [comment]
Thanks for using tocbot. I just updated the readme to explain how to handle fixed headers better. https://github.com/tscanlin/tocbot#fixed-headers

Basically, use CSS similar to the following:

```css
h1::before, h2::before, h3::before, h4::before, h5::before, h6::before {
    display: block;
    content: " ";
    height: 60px;
    margin-top: -60px;
    visibility: hidden;
}
```

Let me know how that works for you.
